exports.macros = {
  '\\Z': '\\mathbf{Z}',
  '\\Q': '\\mathbf{Q}',
  '\\R': '\\mathbf{R}',
  '\\C': '\\mathbf{C}',
  '\\G': '\\mathbf{G}',
  '\\F': '\\mathbf{F}',
  '\\P': '\\mathbf{P}',
  '\\A': '\\mathbf{A}',
  '\\nZ': '\\mathbf{Z}/#1\\mathbf{Z}',
  '\\nZtimes': '(\\mathbf{Z}/#1\\mathbf{Z})^\\times',

  '\\mb': '\\mathbf{#1}',
  '\\mc': '\\mathcal{#1}',
  '\\mf': '\\mathfrak{#1}',
  '\\ms': '\\mathscr{#1}',
  '\\mr': '\\mathrm{#1}',

  '\\pd': '\\frac{\\partial{#1}}{\\partial{#2}}',
  '\\dx': '\\,\\mathrm{d}x',
  '\\dy': '\\,\\mathrm{d}y',
  '\\dz': '\\,\\mathrm{d}z',
  '\\dt': '\\,\\mathrm{d}t',
  '\\dtheta': '\\,\\mathrm{d}\\theta',

  '\\Re': '\\operatorname{Re}',
  '\\Im': '\\operatorname{Im}',
  '\\coker': '\\operatorname{coker}',
  '\\tr': '\\operatorname{tr}',
  '\\im': '\\operatorname{im}',
  '\\span': '\\operatorname{span}',
  '\\la': '\\left\\langle',
  '\\ra': '\\right\\rangle',
  '\\ad': '\\operatorname{ad}',
  '\\Ad': '\\operatorname{Ad}',

  '\\Spec': '\\operatorname{Spec}',
  '\\Ext': '\\operatorname{Ext}',
  '\\Tor': '\\operatorname{Tor}',
  '\\Hom': '\\operatorname{Hom}',
  '\\Aut': '\\operatorname{Aut}',
  '\\End': '\\operatorname{End}',
  '\\Gal': '\\operatorname{Gal}',
  '\\Ind': '\\operatorname{Ind}',
  '\\vol': '\\operatorname{vol}',
  '\\id': '\\operatorname{id}',
  '\\ord': '\\operatorname{ord}',
  '\\ch': '\\operatorname{ch}',
  '\\Der': '\\operatorname{Der}',

  '\\GL': '\\operatorname{GL}',
  '\\PGL': '\\operatorname{PGL}',
  '\\SL': '\\operatorname{SL}',
  '\\PSL': '\\operatorname{PSL}',
  '\\SU': '\\operatorname{SU}',
  '\\U': '\\operatorname{U}',
  '\\GU': '\\operatorname{GU}',
  '\\O': '\\operatorname{O}',
  '\\SO': '\\operatorname{SO}',
  '\\Sp': '\\operatorname{Sp}',
  '\\GSp': '\\operatorname{GSp}',

  '\\sl': '\\mathfrak{sl}',
  '\\gl': '\\mathfrak{gl}',
  '\\sp': '\\mathfrak{sp}',
  '\\so': '\\mathfrak{so}',
}
